fieldLayouts:
  e162d1aa-f268-4380-bd89-f7b58fa5beb2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: a5ca1bca-5e6a-41c6-94a1-4e810b5de66a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 51dd793a-7581-4872-b208-57af48f9ce9e
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: images
transformSubpath: ''
