fieldLayouts:
  ccf372bc-af2e-4923-8301-787fcd2a49d8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d3509be9-1015-4647-bfbd-8d34e3e6779b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e0f4bc6a-1d08-4ea1-af1f-a5996514e1ea # Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4dd7936e-7c47-473b-90a8-bf27d603bb28
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b6d32ac7-0370-4dce-96a6-768ce2bdd309 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a60d71c0-f98f-46e0-982e-6ac56f94e08a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 041a02da-eb13-40fd-a5b4-cf7610dfd82d # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97575d71-d747-4588-8384-cd68392b4579
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 41af1cc1-d004-4210-9867-11f12826114c
        userCondition: null
handle: about
hasTitleField: false
name: About
section: 0dab8dda-312e-4647-a4f8-8879ffa11af1 # About
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
